version: "3"

services:
  storage_service: &storage_service
    build:
      context: .
      dockerfile: ./compose/storage_service/Dockerfile
    image: storage-service_api
    container_name: storage_service_api
    volumes:
      - .:/storage_service
      - ./tmp/img:/storage_service/tmp/img
      - ./tmp/files:/storage_service/tmp/files
    ports:
      - "8000:8000"
    command: /storage_service_start
    stdin_open: true
    tty: true
