version: "3"

services:
  storage_service: &storage_service
    build:
      context: .
      dockerfile: ./compose/storage_service/Dockerfile
    image: storage-service_api
    container_name: storage_service_api
    volumes:
      - .:/storage_service
      - ./tmp/img:/storage_service/tmp/img
      - ./tmp/files:/storage_service/tmp/files
    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
      CELERY_FLOWER_USER: ${{ secrets.CELERY_FLOWER_USER }}
      CELERY_FLOWER_PASSWORD: ${{ secrets.CELERY_FLOWER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      TMP_FILES: ${{ secrets.TMP_FILES }}
      TMP_IMG: ${{ secrets.TMP_IMG }}
    ports:
      - "8000:8000"
    command: /storage_service_start
    stdin_open: true
    tty: true
