version: "3"

services:
  process_service: &process_service
    build:
      context: .
      dockerfile: ./compose/process_service/Dockerfile
    image: process-service_api
    container_name: process_service_api
    volumes:
      - .:/process_service
      - ./process_service/tmp/compressed:/process_service/tmp/compressed
      - ./process_service/tmp/rotated:/process_service/tmp/rotated
      - ./process_service/tmp/thumbnailed:/process_service/tmp/thumbnailed
      - ./process_service/tmp/filtered:/process_service/tmp/filtered
    ports:
      - "9000:9000"
    command: /process_service_start
    stdin_open: true
    tty: true
