version: "3"

services:
  process_service: &process_service
    build:
      context: .
      dockerfile: ./compose/process_service/Dockerfile
    image: process-service_api
    container_name: process_service_api
    volumes:
      - .:/process_service
      - ./tmp/img:/process_service/tmp/img
      - ./tmp/files:/process_service/tmp/files
    ports:
      - "9000:9000"
    command: /process_service_start
    stdin_open: true
    tty: true
