version: "3"

services:
  process_service: &process_service
    build:
      context: .
      dockerfile: ./compose/process_service/Dockerfile
    image: process_service
    container_name: process_service
    volumes:
      - .:/process_service
      - ./process_service/tmp/img:/process_service/tmp/img
      - ./process_service/tmp/files:/process_service/tmp/files
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: /process_service_start
    stdin_open: true
    tty: true
