version: "3"

services:
  api: &process_service
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: process_sevice_api
    container_name: process_service_api
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: /start
    stdin_open: true
    tty: true

  redis:
    image: redis
    container_name: process_service_redis
    command: --port 6380
    ports:
      - "6380:6380"

  celeryworker:
    <<: *process_service
    image: process_service_celeryworker
    container_name: process_service_celeryworker
    depends_on:
      - redis
      - api
    ports: []
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: /start-celeryworker

  flower:
    <<: *process_service
    image: process_service_flower
    container_name: process_service_flower
    ports:
      - "5556:5556"
    depends_on:
      - redis
      - celeryworker
    command: /start-flower
