version: "3"

services:
  api: &fastAPI
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: storage_service_api
    container_name: storage_service_api
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./tmp/img:/app/tmp/img
      - ./tmp/files:/app/tmp/files
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start
    stdin_open: true
    tty: true

  redis:
    image: redis
    container_name: storage_service_redis
    ports:
      - "6379:6379"

  celeryworker:
    <<: *fastAPI
    image: storage_service-celeryworker
    container_name: storage_service_celeryworker
    depends_on:
      - redis
      - api
    ports: []
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: /start-celeryworker

  flower:
    <<: *fastAPI
    image: storage_service_flower
    container_name: storage_service_flower
    ports:
      - "5555:5555"
    depends_on:
      - celeryworker
    command: /start-flower
