#!/bin/bash

set -o errexit
set -o nounset

until timeout 5s celery -A config.celery_app inspect ping; do
    >&2 echo "Celery workers not available"
done

echo "[* Flower]: Starting Flower"
celery \
    -A config.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"