#!/bin/bash

set -o errexit
set -o nounset


celery \
    -A config.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --port=5565 \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"