name: Storage Service CI/CD.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Filter for storage service
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            storage_service:
              - 'storage_service/*'

      - name: Startup Common Services
        if: steps.filter.outputs.storage_service == 'true'
        run: docker-compose -f common.test.yml up -d

      - name: Startup Storage Services
        if: steps.filter.outputs.storage_service == 'true'
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Show Common Services Logs
        if: steps.filter.outputs.storage_service == 'true'
        run: docker-compose -f common.test.yml logs

      - name: Show Storage Services Logs
        if: steps.filter.outputs.storage_service == 'true'
        run: docker-compose -f docker-compose.test.yml logs

      - name: Run Tests and Linting Checks
        if: steps.filter.outputs.storage_service == 'true'
        run: docker-compose -f docker-compose.test.yml exec -T storage_service pytest
