name: Image Storage Service CI/CD.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: storage-service
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Filter for storage service
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            storage-service:
              - 'storage-service/*'

      - name: Startup Services
        if: steps.filter.outputs.storage-service == 'true'
        run: docker-compose -f storage-service/docker-compose.test.yml up -d

      - name: Show Services Logs
        if: steps.filter.outputs.storage-service == 'true'
        run: docker-compose -f docker-compose.test.yml logs

      - name: Run Tests and Linting Checks
        if: steps.filter.outputs.storage-service == 'true'
        run: docker-compose -f docker-compose.test.yml exec -T django python manage.py test
